# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 551ebd6cc40dedd8b948183ba63f2353012a962e130583cd68bddd09ec3a44e3f78bc34f2ff851c38745a0cd084424eb4941f56def6ff38911cc2edbc0f3d4e2

test:
  secret_key_base: 1dc13f8cc3f470637b63709c32738ec3e66beac25d4a844563712fbf82687f77bfc8a2b0828d1a70561ac911c13631305367f59fc8d82adc984e0949e92c44ef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
